name: Deploy Helm Chart

on:
  push:
    branches:
      - main  # Déclenche le workflow quand on push sur main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: v1.25.0

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install monitoring ./charts/monitoring -n monitoring --create-namespace
