name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Kubernetes
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
        run: |
          echo "$KUBECONFIG_BASE64" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Verify Kubernetes cluster access
        run: |
          kubectl get nodes

      - name: Deploy Helm chart
        run: |
          helm upgrade --install monitoring ./charts/monitoring -n monitoring --create-namespace
